package com.testehan.security;

import com.j256.twofactorauth.TimeBasedOneTimePasswordUtil;

import java.security.GeneralSecurityException;

public class TwoFactorAuthenticationExample {

    public static void main(String[] args) throws GeneralSecurityException, InterruptedException {

        // 1. Store the secret key in the database associated with the user account (userMax in our case).
        final String passBase32 = TimeBasedOneTimePasswordUtil.generateBase32Secret();
        System.out.println(passBase32);

        // 2. use the builder to construct the url to the QR image; this image is scanned with Google Authenticator app
        // the link generated by the library is not correct for some reason..Plus i wanted to practice my builder skills :)
        URLBuilder.Builder builder = new URLBuilder.Builder(passBase32,"userMax");
        final String url = builder.withQrSize(500).withPeriodInSeconds(60).build().getQrImageUrl();
        System.out.println(url);

        Thread.sleep(15000);  // because the code is generated very fast, and by the time i click on the link and scan,
                                    // the next code will appear

        // 3. The user will input your app/website the code from Google Authenticator app. That code will be compared
        // against the expectedCode from below
        final String expectedCode = TimeBasedOneTimePasswordUtil.generateCurrentNumberString(passBase32);
        System.out.println(expectedCode);
    }

}
